MVCAssignment/Models/ErrorViewModel.cs
namespace MVCAssignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCAssignment/Models/Fever.cs
using System.ComponentModel.DataAnnotations;

namespace MVCAssignment.Models
{
    public class Fever
    {
        //Data Anotation to change tha Property name in display screen
        [Display(Name = "Body Tempreture")]
        public double BTemp { get; set; }

        public string Message { get; set; }

        public string TemperatureUnit { get; set; }
    }
}

MVCAssignment/Models/GGame.cs
using System.ComponentModel.DataAnnotations;

namespace MVCAssignment.Models
{
    public class GGame
    {
        public int SNum { get; set; }

        [Display(Name = "Your Guess")]
        public int GNum { get; set; }
        public string Message { get; set; }

        public int Attemts {  get; set; }
    }
}

MVCAssignment/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace MVCAssignment.Models
{
    public class Student
    {
        //    [Required] public int Id { get; set; }
        public int SId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public int Age { get; set; }


        

        public Student()
        {

        }

        public Student(int sId, string name, string gender, int age)
        {
            SId = sId;
            Name = name;
            Gender = gender;
            Age = age;

        }
    }
}

MVCAssignment/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using MVCAssignment.Models;
using System.Xml.Linq;

namespace MVCAssignment.Controllers
{
    public class AssignmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult FeverCheck()
        {
            Fever model = new Fever();
            return View(model);

        }
        [HttpPost]
        public IActionResult FeverCheck(Fever obj)
        {
            if (obj.TemperatureUnit == "Fahrenheit")
            {
                // Convert Fahrenheit to Celsius
                obj.BTemp = (obj.BTemp - 32) * 5 / 9;
            }
            if (obj.BTemp < 36.1)
                obj.Message = "You may have hypothermia or other health issues. Consult with Doctor.";
            else if (obj.BTemp >= 36.1 && obj.BTemp <= 37.2)
                obj.Message = "Not to worry! You do not have fever. ";
            else if (obj.BTemp >= 37.3 && obj.BTemp <= 38)
                obj.Message = "You have fever, Take rest. ";
            else if (obj.BTemp > 38)
                obj.Message = "You have high fever. Consult a doctor as soon as possiable.";
            return View(obj);
        }


        public IActionResult GuessGame()
        {
            int Attempts;
            GGame model = new GGame();
            Random rnd = new Random();
            int sNum = rnd.Next(1, 501);
            model.SNum = sNum;
            HttpContext.Session.SetInt32("SNumber", sNum);
            return View(model);
        }

        [HttpPost]
        public IActionResult GuessGame(GGame obj)
        {
            
            obj.SNum = (int)HttpContext.Session.GetInt32("SNumber");
            int counter = (int)(HttpContext.Session.GetInt32("GuessAttempts") ?? 0); // Retrieve existing counter or default to 0

            if (obj.GNum > obj.SNum)
            {
                obj.Message = "Your guess is hihg!";
            }
            else if (obj.GNum < obj.SNum)
            {
                obj.Message = "Your guess is low.";
            }
            else
            {
                obj.Message = "You guessed it correct!";
                HttpContext.Session.Clear();
            }

            counter++;
            HttpContext.Session.SetInt32("GuessAttempts", counter); // Store updated counter in session
            obj.Attemts = counter;
            return View(obj);
        }

        public IActionResult Greet()
        {
            ViewBag.vbMsg = "Welcome To My MVC Assignment and this message is through ViewBag.";
            ViewData["vdMsg"] = "Welcome To My MVC Assignment and this message is through ViewData";
            TempData["tdMsg"] = "Welcome To My MVC Assignment and this message is through TempData";
            return View();
        }
    }
}

MVCAssignment/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCAssignment.Models;
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace MVCAssignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCAssignment/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using MVCAssignment.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MVCAssignment.Controllers
{
    
    public class StudentController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public StudentController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        List<Student> Students = new List<Student>()
        {
            new Student(1, "Anju", "Female", 20),
            new Student(2, "Igore", "Female", 21),
            new Student(3, "Aassa", "Female", 19),
            new Student(4, "Erik", "Male", 22),
            new Student(5, "Shehan", "Male", 22),
            new Student(6, "Shradha", "Female", 20),
            new Student(7, "Dilip", "Male", 25),
            new Student(8, "Helena", "Female", 20),
            new Student(9, "Ingela", "Female", 21)
        };
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("sList") != null)
            {
                List<Student> StudentList =
                    JsonConvert.DeserializeObject<List<Student>>(HttpContext.Session.GetString("sList"));

                return View(StudentList);
            }
            else
            {
                return View(Students);
            }

        }


        public IActionResult Details(int id)
        {
            //var student = Students[id -1];
           
                var student = Students.FirstOrDefault(s => s.SId == id);
            return View(student);
                
        }
        public IActionResult StudentList()
        {

            var studentList = Students.OrderBy(s => s.Name).ToList();
            return View(Students);
        }

        public IActionResult DisplayStudents()
        {
            
            return View(Students);
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Student student)
        {



            // HttpContext.Session.SetString("sList", JsonConvert.SerializeObject(Students));

            // var s = Students.LastOrDefault();
            //  student.SId = student.SId + 1;

            if (HttpContext.Session.GetString("sList") != null)
            {
                List<Student> StudentList = JsonConvert.DeserializeObject<List<Student>>(HttpContext.Session.GetString("sList"));
                var s = StudentList.LastOrDefault();
                student.SId = s.SId + 1;

                StudentList.Add(student);
                HttpContext.Session.SetString("sList", JsonConvert.SerializeObject(StudentList));
            }
            else
            {
                var s = Students.LastOrDefault();
                student.SId = s.SId + 1;
                Students.Add(student);
                HttpContext.Session.SetString("sList", JsonConvert.SerializeObject(Students));
            }
            // Students.Add(student);
            return RedirectToAction("Index");
        }
    }
}

MVCAssignment/Views/Assignment/FeverCheck.cshtml
@model MVCAssignment.Models.Fever

@{
    ViewData["Title"] = "FeverCheck";
}

<h1>Take a Free Fever Test For You</h1>
<h1 style="background-color:red">@Model.Message</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="FeverCheck">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group top-bottom-margin">
                <label><input type="radio" name="TemperatureUnit" value="Celsius" checked> Celsius</label>
                <label><input type="radio" name="TemperatureUnit" value="Fahrenheit"> Fahrenheit</label>

            </div>
            <div class="form-group top-bottom-margin">
                <label asp-for="BTemp" class="control-label"></label>
                <input asp-for="BTemp" class="form-control" />
                <span asp-validation-for="BTemp" class="text-danger"></span>
            </div>
           
            <div class="form-group top-bottom-margin">
                <input type="submit" value="Take a fever test" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="top-bottom-margin">
    <a asp-action="Index">Back to Assignment</a>
</div>

MVCAssignment/Views/Assignment/Greet.cshtml
@{
    ViewData["Title"] = "Greet";
}
<div><h1>Greet Using ViewBag</h1></div>

<h3 style="background-color:darkcyan">@ViewBag.vbMsg</h3>
<h3 style="background-color:crimson">@ViewData["vdMsg"]</h3>
<h3 style="background-color:darkgoldenrod">@TempData["tdMsg"]</h3>

MVCAssignment/Views/Assignment/GuessGame.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@model MVCAssignment.Models.GGame

@{
    ViewData["Title"] = "GuessGame";
}

<h2>I choose a number between 1 to 500 try to guess it!</h2>
<hr />

<div class="bg-danger"><h3>@Model.Message</h3></div>
<p>Number of attempts: @Model.Attemts</p>
<hr />


<div class="row">
    <div class="col-md-4">
        <form asp-action="GuessGame">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @{
                if (HttpContextAccessor.HttpContext.Session.GetInt32("SNumber") != null)
                {
                    <div class="form-group top-bottom-margin">
                        <label asp-for="GNum" class="control-label"></label>
                        <input asp-for="GNum" class="form-control" />
                        <span asp-validation-for="GNum" class="text-danger"></span>
                    </div>

                    <div class="form-group top-bottom-margin">
                        <input type="submit" value="Guess" class="btn btn-primary" />
                    </div>
                }
                else{
                    // <div class="col-md-4">
                    //     @Html.ActionLink("Re play", "GuessGame", "Assignment", null, new { @class = "btn btn-success" })
                    // </div>
                    // <div class="col-md-4">
                    //     @Html.ActionLink("Re play", "GuessGame", "Assignment", new { @class = "btn btn-success" })
                    // </div>
                    <a class="btn btn-primary" asp-controller="Assignment" asp-action="GuessGame"> Re Play </a>
                }
            }
            
        </form>
    </div>
</div>

<div class="top-bottom-margin">
    <a asp-action="Index">Back to Assignment</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCAssignment/Views/Assignment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}



<h1>Exercises</h1>

<div class="top-bottom-margin">
    @Html.ActionLink("Exercise - 1", "Greet", "Assignment", null, new { @class = "btn btn-warning" })

</div>

<div class="top-bottom-margin">
   @*  <a class="btn btn-primary" asp-area="" asp-controller="Assignment" asp-action="FeverCheck"> Ex2- Fever Test </a>
    <a class="btn btn-warning" href="/Assignment/FeverCheck">Ex2- Fever Test </a> *@
    @Html.ActionLink("Ex2- Fever Test", "FeverCheck", "Assignment", null, new { @class = "btn btn-success" })
</div>

<div class="top-bottom-margin">
    @Html.ActionLink("Ex3- Guess Game", "GuessGame", "Assignment", null, new { @class = "btn btn-info" })

</div>

MVCAssignment/Views/Greet/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

MVCAssignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCAssignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="background">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCAssignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="Index">Assignment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Ex-4-Partial View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted background">
        <div class="container">
            &copy; 2024 - MVCAssignment - Anju <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCAssignment/Views/Shared/_StudentPartial.cshtml
@model MVCAssignment.Models.Student

<div>
    <h4>@Model.Name</h4>

    <dl class="row">


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SId)
        </dd>
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        
    </dl>

</div>

MVCAssignment/Views/Student/Create.cshtml
@model MVCAssignment.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            
            <div class="form-group top-bottom-margin">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group top-bottom-margin">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group top-bottom-margin">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            
            <div class="form-group top-bottom-margin">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <br />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVCAssignment/Views/Student/Details.cshtml
@model MVCAssignment.Models.Student
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

@Html.Partial("_StudentPartial", Model)

MVCAssignment/Views/Student/DisplayStudents.cshtml
@model IEnumerable<MVCAssignment.Models.Student>

@{
    ViewData["Title"] = "DisplayStudents";
}

@* <h1>DisplayStudents</h1> *@

@foreach (var student in Model)
{@* 
      *@ @Html.Partial("_StudentPartial",student); 

    <Partial name="_StudentPartial" model="student"></Partial>

    @*  @await Html.PartialAsync("_StudentPartial",student); *@

    <hr />
}

MVCAssignment/Views/Student/Index.cshtml
@model IEnumerable<MVCAssignment.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h2 style="background-color:darkgray">Click on details to see partial view </h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
           @*  <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
           @*  <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td> *@
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { id=item.SId }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
@* <div class="top-bottom-margin">
    @Html.ActionLink("Eercise - 4 Partial View", "Details", "Assignment", null, new { @class = "btn btn-success" })

</div> *@

MVCAssignment/Views/Student/StudentList.cshtml
@model IEnumerable<MVCAssignment.Models.Student>

@{
    ViewData["Title"] = "StudentList";
}

<h1>StudentList</h1>

@* @foreach(var s in Model)
{
    <h3>@s.SId : @s.Name</h3>
} *@


@{
    int i = 1;
}
@foreach (var s in Model)
{
    <h3>@i) &nbsp;&nbsp; @s.SId : @s.Name</h3>
    i = i + 1;
}